using System;

namespace ExtensionScript
{
    public static class KickMSG
    {
        private static readonly Random rng = new Random();
        private static readonly string[] msg = { "@PLATFORM_STEAM_CONNECT_FAIL", "@EXE_ERR_BANNED_TEMP", "@EXE_ERR_BANNED_PERM", "@PLATFORM_STEAM_KICK_CHEAT", "@PLATFORM_STEAM_AUTH_DENIED", "@MENU_NO_CLAN_DESCRIPTION",
        "@EXE_TRANSMITERROR", "@EXE_SERVERISFULL", "@EXE_SV_INFO_SERVERNAME", "@EXE_MATCHENDED", "@MPUI_PARTY_LOST_HOST", "@MENU_VAULT_NOGUESTACCOUNTS", "@MP_BUILDEXPIRED", "@MP_HOST_CHANGING_SETTING",
        "@MP_AUTH_NOT_ENTITLED", "@MENU_ONLINEVAULT_RESTRICTED", "@MENU_ONLINEVAULT_MPNOTALLOWED", "@EXE_SV_INFO_MAXRATE", "@MPUI_MAKEHOSTFAILED", "@MPUI_MAKEHOSTTIMEOUT", "@MP_BETACLOSED",
        "@MP_NOGOODHOST", "@MP_BANNED", "@MENU_VAULT_MUSTLOGIN", "@MP_ENDED_GAME_MIGRATION_FAILED"};

        public static string GetRandomMSG() => msg[rng.Next(msg.Length)];
    }
}
